# Zomato Chennai Data Analysis

In [1]:
# importing the libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.io as pio

pio.renderers.default = 'svg'

In [2]:
# load the dataset

raw_df = pd.read_csv("Zomato Chennai Listing 2020.csv")

In [3]:
raw_df.head()

,Zomato URL,Name of Restaurant,Address,Location,Cuisine,Top Dishes,Price for 2,Dining Rating,Dining Rating Count,Delivery Rating,Delivery Rating Count,Features
0,https://www.zomato.com/chennai/yaa-mohaideen-b...,Yaa Mohaideen Briyani,"336 & 338, Main Road, Pallavaram, Chennai",Pallavaram,['Biryani'],"['Bread Halwa', ' Chicken 65', ' Mutton Biryan...",500.0,4.3,1500,4.3,9306,"['Home Delivery', 'Indoor Seating']"
1,https://www.zomato.com/chennai/sukkubhai-biriy...,Sukkubhai Biriyani,"New 14, Old 11/3Q, Railway Station Road, MKN ...",Alandur,"['Biryani', ' North Indian', ' Mughlai', ' Des...","['Beef Biryani', ' Beef Fry', ' Paratha', ' Pa...",1000.0,4.4,3059,4.1,39200,"['Home Delivery', 'Free Parking', 'Table booki..."
2,https://www.zomato.com/chennai/ss-hyderabad-bi...,SS Hyderabad Biryani,"98/339, Arcot Road, Opposite Gokulam Chit Fun...",Kodambakkam,"['Biryani', ' North Indian', ' Chinese', ' Ara...","['Brinjal Curry', ' Tandoori Chicken', ' Chick...",500.0,4.3,1361,4.4,10500,"['Home Delivery', 'Indoor Seating']"
3,https://www.zomato.com/chennai/kfc-perambur,KFC,"10, Periyar Nagar, 70 Feet Road, Near Sheeba ...",Perambur,"['Burger', ' Fast Food', ' Finger Food', ' Bev...",['Zinger Burger'],500.0,4.0,1101,4.0,11200,"['Home Delivery', 'Free Parking', 'Card Upon D..."
4,https://www.zomato.com/chennai/tasty-kitchen-p...,Tasty Kitchen,"135B, SRP Colony, Peravallur, Near Perambur, ...",Perambur,"['Chinese', ' Biryani', ' North Indian', ' Che...","['Mutton Biryani', ' Chicken Rice', ' Tomato R...",450.0,4.2,617,4.1,22400,"['Home Delivery', 'Indoor Seating']"

# Getting Basic Information about the Dataset

In [4]:
# To get the number of rowns and columns

raw_df.shape

(12032, 12)

In [5]:
# Overview to see the column name, data type, missing values.

raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12032 entries, 0 to 12031
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Zomato URL             12032 non-null  object
 1   Name of Restaurant     12032 non-null  object
 2   Address                12032 non-null  object
 3   Location               12032 non-null  object
 4   Cuisine                12032 non-null  object
 5   Top Dishes             12032 non-null  object
 6   Price for 2            12032 non-null  float64
 7   Dining Rating          6681 non-null   float64
 8   Dining Rating Count    11812 non-null  object
 9   Delivery Rating        6181 non-null   float64
 10  Delivery Rating Count  11812 non-null  object
 11  Features               12032 non-null  object
dtypes: float64(3), object(9)
memory usage: 1.1+ MB

In [6]:
raw_df.describe()

        Price for 2  Dining Rating  Delivery Rating
count  12032.000000    6681.000000      6181.000000
mean     397.611370       3.387756         3.805290
std      332.045938       0.558181         0.374213
min       40.000000       0.300000         0.300000
25%      200.000000       3.100000         3.600000
50%      300.000000       3.500000         3.900000
75%      450.000000       3.800000         4.000000
max     5000.000000       4.900000         4.700000

# Cleaning the Dataset

## a. Removing the redundunt rows of data

In [7]:
# Dropping columns which are not required for further analysis

raw_df.drop(['Zomato URL', 'Address'], axis=1, inplace=True)

In [8]:
raw_df.head()

,Name of Restaurant,Location,Cuisine,Top Dishes,Price for 2,Dining Rating,Dining Rating Count,Delivery Rating,Delivery Rating Count,Features
0,Yaa Mohaideen Briyani,Pallavaram,['Biryani'],"['Bread Halwa', ' Chicken 65', ' Mutton Biryan...",500.0,4.3,1500,4.3,9306,"['Home Delivery', 'Indoor Seating']"
1,Sukkubhai Biriyani,Alandur,"['Biryani', ' North Indian', ' Mughlai', ' Des...","['Beef Biryani', ' Beef Fry', ' Paratha', ' Pa...",1000.0,4.4,3059,4.1,39200,"['Home Delivery', 'Free Parking', 'Table booki..."
2,SS Hyderabad Biryani,Kodambakkam,"['Biryani', ' North Indian', ' Chinese', ' Ara...","['Brinjal Curry', ' Tandoori Chicken', ' Chick...",500.0,4.3,1361,4.4,10500,"['Home Delivery', 'Indoor Seating']"
3,KFC,Perambur,"['Burger', ' Fast Food', ' Finger Food', ' Bev...",['Zinger Burger'],500.0,4.0,1101,4.0,11200,"['Home Delivery', 'Free Parking', 'Card Upon D..."
4,Tasty Kitchen,Perambur,"['Chinese', ' Biryani', ' North Indian', ' Che...","['Mutton Biryani', ' Chicken Rice', ' Tomato R...",450.0,4.2,617,4.1,22400,"['Home Delivery', 'Indoor Seating']"

## b. Removing Null records

In [9]:
# To get Null values count

raw_df.isnull().sum()

Name of Restaurant          0
Location                    0
Cuisine                     0
Top Dishes                  0
Price for 2                 0
Dining Rating            5351
Dining Rating Count       220
Delivery Rating          5851
Delivery Rating Count     220
Features                    0
dtype: int64

In [10]:
# Replacing the null records with NA

raw_df = raw_df.fillna('0')

In [11]:
# Confirming all the null records are replaced

raw_df.isnull().sum()

Name of Restaurant       0
Location                 0
Cuisine                  0
Top Dishes               0
Price for 2              0
Dining Rating            0
Dining Rating Count      0
Delivery Rating          0
Delivery Rating Count    0
Features                 0
dtype: int64

## c. Converting the DataTypes of numerical columns to numeric dataype

In [12]:
# Checking for text values in 'Dining Rating Count' column before converting it to numeric datatype

raw_df['Dining Rating Count'].value_counts()

Dining Rating Count
Does not offer Dining        2603
Not enough Dining Reviews    2528
4                             339
5                             271
6                             248
                             ...
877                             1
897                             1
872                             1
1197                            1
224                             1
Name: count, Length: 793, dtype: int64

In [13]:
# Replacing the text values with '0'

raw_df['Dining Rating Count'] = raw_df['Dining Rating Count'].replace(to_replace = ['Does not offer Dining','Not enough Dining Reviews'],value = 0)

In [14]:
# Checking for text values in 'Delivery Rating Count' column before converting it to numeric datatype

raw_df['Delivery Rating Count'].value_counts()

Delivery Rating Count
Not enough Delivery Reviews    3379
Does not offer Delivery        2252
0                               239
27                               34
40                               30
                               ...
7705                              1
6374                              1
3677                              1
588                               1
1617                              1
Name: count, Length: 2281, dtype: int64

In [15]:
# Replacing the text values with '0'

raw_df['Delivery Rating Count'] = raw_df['Delivery Rating Count'].replace(to_replace=['Not enough Delivery Reviews','Does not offer Delivery'],value=0)

In [16]:
# Changing Data type of the numerical columns

raw_df['Dining Rating Count'] = raw_df['Dining Rating Count'].astype('int64')
raw_df['Delivery Rating Count'] = raw_df['Delivery Rating Count'].astype('int64')

In [17]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12032 entries, 0 to 12031
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Name of Restaurant     12032 non-null  object
 1   Location               12032 non-null  object
 2   Cuisine                12032 non-null  object
 3   Top Dishes             12032 non-null  object
 4   Price for 2            12032 non-null  float64
 5   Dining Rating          12032 non-null  object
 6   Dining Rating Count    12032 non-null  int64
 7   Delivery Rating        12032 non-null  object
 8   Delivery Rating Count  12032 non-null  int64
 9   Features               12032 non-null  object
dtypes: float64(1), int64(2), object(7)
memory usage: 940.1+ KB

In [18]:
raw_df['Dining Rating'].value_counts()

Dining Rating
0      5351
3.6     584
3.5     553
3.7     525
3.4     500
3.3     463
3.8     460
3.2     433
3.9     379
3.1     363
2.0     354
3.0     302
4.0     288
2.9     257
4.1     221
2.8     192
4.2     142
2.7     138
4.3     105
2.6      99
2.5      71
4.4      61
2.4      46
4.5      36
2.3      32
2.2      20
4.6      17
4.7      12
2.1      10
4.9       7
4.8       4
1.9       3
1.7       2
0.3       1
1.0       1
Name: count, dtype: int64